Importing the ldependies

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn .model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

Load the dataset

In [2]:
fifa_23 =pd.read_csv('/content/FIFA23_official_data.csv')

Understand the Dataset

In [3]:
fifa_23.head()

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,Real Face,Position,Joined,Loaned From,Contract Valid Until,Height,Weight,Release Clause,Kit Number,Best Overall Rating
0,209658,L. Goretzka,27,https://cdn.sofifa.net/players/209/658/23_60.png,Germany,https://cdn.sofifa.net/flags/de.png,87,88,FC Bayern München,https://cdn.sofifa.net/teams/21/30.png,...,Yes,"<span class=""pos pos28"">SUB","Jul 1, 2018",NaN,2026,189cm,82kg,€157M,8.0,NaN
1,212198,Bruno Fernandes,27,https://cdn.sofifa.net/players/212/198/23_60.png,Portugal,https://cdn.sofifa.net/flags/pt.png,86,87,Manchester United,https://cdn.sofifa.net/teams/11/30.png,...,Yes,"<span class=""pos pos15"">LCM","Jan 30, 2020",NaN,2026,179cm,69kg,€155M,8.0,NaN
2,224334,M. Acuña,30,https://cdn.sofifa.net/players/224/334/23_60.png,Argentina,https://cdn.sofifa.net/flags/ar.png,85,85,Sevilla FC,https://cdn.sofifa.net/teams/481/30.png,...,No,"<span class=""pos pos7"">LB","Sep 14, 2020",NaN,2024,172cm,69kg,€97.7M,19.0,NaN
3,192985,K. De Bruyne,31,https://cdn.sofifa.net/players/192/985/23_60.png,Belgium,https://cdn.sofifa.net/flags/be.png,91,91,Manchester City,https://cdn.sofifa.net/teams/10/30.png,...,Yes,"<span class=""pos pos13"">RCM","Aug 30, 2015",NaN,2025,181cm,70kg,€198.9M,17.0,NaN
4,224232,N. Barella,25,https://cdn.sofifa.net/players/224/232/23_60.png,Italy,https://cdn.sofifa.net/flags/it.png,86,89,Inter,https://cdn.sofifa.net/teams/44/30.png,...,Yes,"<span class=""pos pos13"">RCM","Sep 1, 2020",NaN,2026,172cm,68kg,€154.4M,23.0,NaN

In [4]:
fifa_23.shape

(17660, 29)

In [5]:
fifa_23.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17660 entries, 0 to 17659
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        17660 non-null  int64
 1   Name                      17660 non-null  object
 2   Age                       17660 non-null  int64
 3   Photo                     17660 non-null  object
 4   Nationality               17660 non-null  object
 5   Flag                      17660 non-null  object
 6   Overall                   17660 non-null  int64
 7   Potential                 17660 non-null  int64
 8   Club                      17449 non-null  object
 9   Club Logo                 17660 non-null  object
 10  Value                     17660 non-null  object
 11  Wage                      17660 non-null  object
 12  Special                   17660 non-null  int64
 13  Preferred Foot            17660 non-null  object
 14  International Reputation  17660 non-null  float64
 15  Weak Foot                 17660 non-null  float64
 16  Skill Moves               17660 non-null  float64
 17  Work Rate                 17660 non-null  object
 18  Body Type                 17622 non-null  object
 19  Real Face                 17622 non-null  object
 20  Position                  17625 non-null  object
 21  Joined                    16562 non-null  object
 22  Loaned From               694 non-null    object
 23  Contract Valid Until      17299 non-null  object
 24  Height                    17660 non-null  object
 25  Weight                    17660 non-null  object
 26  Release Clause            16509 non-null  object
 27  Kit Number                17625 non-null  float64
 28  Best Overall Rating       21 non-null     object
dtypes: float64(4), int64(5), object(20)
memory usage: 3.9+ MB

In [6]:
fifa_23.isnull().sum()

ID                              0
Name                            0
Age                             0
Photo                           0
Nationality                     0
Flag                            0
Overall                         0
Potential                       0
Club                          211
Club Logo                       0
Value                           0
Wage                            0
Special                         0
Preferred Foot                  0
International Reputation        0
Weak Foot                       0
Skill Moves                     0
Work Rate                       0
Body Type                      38
Real Face                      38
Position                       35
Joined                       1098
Loaned From                 16966
Contract Valid Until          361
Height                          0
Weight                          0
Release Clause               1151
Kit Number                     35
Best Overall Rating         17639
dtype: int64

 Preprocess the Data

In [12]:
# Drop non-informative or unique identifier columns
fifa_23.drop(['Photo', 'Flag', 'Club Logo'], axis=1, inplace=True)

KeyError: "['Photo', 'Flag', 'Club Logo'] not found in axis"

In [13]:
fifa_23.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,...,Real Face,Position,Joined,Loaned From,Contract Valid Until,Height,Weight,Release Clause,Kit Number,Best Overall Rating
0,209658,L. Goretzka,27,Germany,87,88,FC Bayern München,€91M,€115K,2312,...,Yes,"<span class=""pos pos28"">SUB","Jul 1, 2018",NaN,2026,189cm,82kg,€157M,8.0,NaN
1,212198,Bruno Fernandes,27,Portugal,86,87,Manchester United,€78.5M,€190K,2305,...,Yes,"<span class=""pos pos15"">LCM","Jan 30, 2020",NaN,2026,179cm,69kg,€155M,8.0,NaN
2,224334,M. Acuña,30,Argentina,85,85,Sevilla FC,€46.5M,€46K,2303,...,No,"<span class=""pos pos7"">LB","Sep 14, 2020",NaN,2024,172cm,69kg,€97.7M,19.0,NaN
3,192985,K. De Bruyne,31,Belgium,91,91,Manchester City,€107.5M,€350K,2303,...,Yes,"<span class=""pos pos13"">RCM","Aug 30, 2015",NaN,2025,181cm,70kg,€198.9M,17.0,NaN
4,224232,N. Barella,25,Italy,86,89,Inter,€89.5M,€110K,2296,...,Yes,"<span class=""pos pos13"">RCM","Sep 1, 2020",NaN,2026,172cm,68kg,€154.4M,23.0,NaN

In [16]:
# Filling missing values (or drop if too many)
fifa_23= fifa_23.dropna()

In [17]:
fifa_23.isnull().sum()

ID                          0
Name                        0
Age                         0
Nationality                 0
Overall                     0
Potential                   0
Club                        0
Value                       0
Wage                        0
Special                     0
Preferred Foot              0
International Reputation    0
Weak Foot                   0
Skill Moves                 0
Work Rate                   0
Body Type                   0
Real Face                   0
Position                    0
Joined                      0
Loaned From                 0
Contract Valid Until        0
Height                      0
Weight                      0
Release Clause              0
Kit Number                  0
Best Overall Rating         0
dtype: int64

Encode categorical Data

In [69]:
from sklearn.preprocessing import LabelEncoder

# Encode only the target variable 'Position' and store the encoder
label_encoders = {}
if 'Position' in fifa_23.columns:
    le = LabelEncoder()
    fifa_23['Position'] = le.fit_transform(fifa_23['Position'])
    label_encoders['Position'] = le

# At this point, other 'object' columns should ideally be handled (cleaned/converted to numeric)
# based on previous steps. We will verify the data types after this cell.

In [52]:
fifa_23.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,...,Real Face,Position,Joined,Loaned From,Contract Valid Until,Height,Weight,Release Clause,Kit Number,Best Overall Rating
7116,270643,7906,24,109,63,67,858,0.0,0.0,1611,...,0,2,2019-01-23,128,2021-01-01,174,67,403000.0,14.0,0
7117,259766,6836,19,144,62,77,122,900000.0,4000.0,1611,...,0,18,2020-07-28,128,2027-01-01,173,73,2300000.0,33.0,0
7118,267481,6713,23,5,68,75,225,2400000.0,500.0,1611,...,0,16,2020-08-01,128,2022-01-01,194,90,5600000.0,25.0,0
7119,257630,7873,20,63,62,75,793,950000.0,5000.0,1611,...,0,18,2020-09-25,128,2026-01-01,185,72,2300000.0,18.0,0
7120,263687,3846,19,5,60,73,86,575000.0,1000.0,1611,...,0,19,2021-07-01,128,2025-01-01,186,69,1200000.0,34.0,0

In [60]:
print(fifa_23.select_dtypes(include='object').columns)

Index([], dtype='object')

: Define Target and Features

In [62]:
X = fifa_23.drop(columns=['Position', 'Name', 'Joined', 'Contract Valid Until'])  # Features
y = fifa_23['Position']  # Target

Train-Test Split

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Applying the navie byies

In [64]:
X_train

,ID,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Skill Moves,Work Rate,Body Type,Real Face,Loaned From,Height,Weight,Release Clause,Kit Number,Best Overall Rating
17596,266803,19,111,55,70,154,250000.0,750.0,807,1,...,1.0,8,5,0,23,195,83,506000.0,90.0,0
13449,256041,24,100,55,58,843,170000.0,800.0,1378,1,...,3.0,8,4,0,50,175,68,225000.0,26.0,0
12035,250875,25,52,63,68,706,650000.0,650.0,1434,1,...,2.0,2,2,0,138,194,80,991000.0,4.0,0
12543,264168,18,52,55,73,693,325000.0,500.0,1415,1,...,3.0,8,1,0,88,177,69,674000.0,41.0,0
14648,255790,22,105,56,65,198,300000.0,500.0,1317,1,...,2.0,8,7,0,1,172,70,705000.0,24.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12850,260253,29,143,64,64,39,500000.0,500.0,1403,1,...,2.0,8,1,0,176,183,74,1100000.0,20.0,0
12307,270119,17,110,51,64,737,130000.0,500.0,1424,1,...,2.0,8,1,0,190,176,68,283000.0,22.0,0
12506,255732,20,141,52,63,206,160000.0,500.0,1417,1,...,2.0,3,4,0,65,178,72,376000.0,29.0,0
7976,255235,18,95,62,72,336,800000.0,550.0,1578,0,...,2.0,2,4,0,13,184,79,1400000.0,24.0,0
14386,261954,21,24,54,63,789,230000.0,1000.0,1333,0,...,2.0,8,7,0,43,180,79,403000.0,16.0,0

In [65]:
y_train

17596    19
13449    18
12035    18
12543    18
14648    18
         ..
12850    21
12307    18
12506    18
7976     18
14386    18
Name: Position, Length: 8435, dtype: int64

In [66]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train, y_train)

# Predict and evaluate
y_pred = nb.predict(X_test)

Evaluate Model

In [67]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.4362256993835941
[[ 20   0   0   0   2   0   0   1   0   0   0   0   0   0   0   0   0   0
   24  25   0   4   2   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    1   3   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   2   0   0   0   0   0   0   0   0   0   0   0   0   0
    2   8   0   0   0   0   0   0   0]
 [  0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0
    0   6   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   5   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    3  14   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    1   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    1   5   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   2   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    1   6   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   5   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    5  17   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   9   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   3   0   0   0   0   0   0   0]
 [ 19   0   0   0   9   2   0   5   0   0   0   1   0   0   0   0   0   0
   73 773   0   5   3   1   0   0   0]
 [  1   0   0   0   5   3   0   0   0   0   0   0   0   0   0   0   0   0
   45 826   0   2   1   0   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0
    5  15   0   0   0   0   0   0   0]
 [  1   0   0   0   2   0   0   2   0   0   0   0   0   0   0   0   0   0
   12  30   0   1   0   0   0   0   0]
 [  2   0   0   0   1   1   0   0   0   0   0   0   0   0   0   0   0   0
    2   3   0   1   0   0   0   0   0]
 [  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   18  24   0   0   0   0   0   0   0]
 [  0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0
    2  19   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    1   3   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   4   0   0   0   0   0   0   0]]
              precision    recall  f1-score   support

           0       0.44      0.26      0.33        78
           1       0.00      0.00      0.00         4
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00        12
           4       0.00      0.00      0.00         7
           5       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         6
           7       0.00      0.00      0.00        17
           8       0.00      0.00      0.00         2
           9       0.00      0.00      0.00         6
          10       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         0
          12       0.00      0.00      0.00         2
          13       0.00      0.00      0.00         7
          14       0.00      0.00      0.00         5
          15       0.00      0.00      0.00        22
          16       0.00      0.00      0.00         9
          17       0.00      0.00      0.00         3
          18       0.37      0.08      0.13       891
          19       0.46      0.94      0.61       883
          20       0.00      0.00      0.00        21
          21       0.08      0.02      0.03        48
          22       0.00      0.00      0.00        10
          23       0.00      0.00      0.00        44
          24       0.00      0.00      0.00        22
          25       0.00      0.00      0.00         4
          26       0.00      0.00      0.00         4

    accuracy                           0.44      2109
   macro avg       0.05      0.05      0.04      2109
weighted avg       0.37      0.44      0.33      2109

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Predictive System

In [71]:
def predict_player_position(player_data, model, label_encoders, feature_columns):
    """
    Predicts the position of a player using the trained Naive Bayes model.

    Args:
        player_data (dict): A dictionary containing the player's attributes (numerical format).
        model: The trained machine learning model (GaussianNB in this case).
        label_encoders (dict): A dictionary of label encoders used for decoding the target variable.
        feature_columns (list): A list of the feature column names in the order the model expects.

    Returns:
        str: The predicted position of the player.
    """
    # Create a pandas DataFrame from the input data
    # Ensure the input data dictionary keys match the feature_columns
    input_df = pd.DataFrame([player_data])

    # Ensure the input DataFrame has the same columns as the training data and in the correct order
    # This is crucial for the model prediction
    input_df = input_df[feature_columns]

    # Make the prediction
    predicted_encoded_position = model.predict(input_df)

    # Decode the predicted position using the stored label encoder for 'Position'
    if 'Position' in label_encoders:
        predicted_position = label_encoders['Position'].inverse_transform(predicted_encoded_position)
        return predicted_position[0]
    else:
        # If 'Position' was not encoded (which it should be based on previous steps), return the raw prediction
        return predicted_encoded_position[0]

# Example usage:
# First, make sure you have the list of feature columns used for training
# You can get this from X_train.columns.tolist() after dropping columns
feature_columns = X_train.columns.tolist()

# Create a dictionary with example player data (replace with actual data)
# The values should be in the numerical format after preprocessing
# You would need to get the numerical values for categorical features from your preprocessed data
# For this example, I'll use numerical values based on the structure of X_train
example_player_data = {
    'ID': 209658,
    'Age': 27,
    'Nationality': 52, # Example numerical value for Germany based on previous encoding
    'Overall': 87,
    'Potential': 88,
    'Club': 21, # Example numerical value for FC Bayern München
    'Value': 91000000.0, # Numerical value for €91M
    'Wage': 115000.0, # Numerical value for €115K
    'Special': 2312,
    'Preferred Foot': 1, # Example numerical value for Right
    'International Reputation': 4.0,
    'Weak Foot': 4.0,
    'Skill Moves': 4.0,
    'Work Rate': 1, # Example numerical value for High/High
    'Body Type': 1, # Example numerical value for Stocky
    'Real Face': 1, # Example numerical value for Yes
    'Loaned From': 128, # Example numerical value for NaN (or a placeholder)
    'Height': 189, # Numerical value for 189cm
    'Weight': 82, # Numerical value for 82kg
    'Release Clause': 157000000.0, # Numerical value for €157M
    'Kit Number': 8.0,
    'Best Overall Rating': 87.0 # Numerical value for 87
}

# Predict the position
# Make sure the 'nb' model is trained before running this
predicted_position = predict_player_position(example_player_data, nb, label_encoders, feature_columns)
print(f"The predicted position for the player is: {predicted_position}")

The predicted position for the player is: 0